version: '3.4'

networks:
  studentappnetwork:

services:
  Database:
    container_name: Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Vezba123!1
    networks:
     - studentappnetwork

  schoolmanagmentsystem:
    container_name: schoolmanagmentsystem
    ports:
     - 8001:80
    image: ${DOCKER_REGISTRY-}schoolmanagmentsystem
    build:
      context: .
      dockerfile: SchoolManagmentSystem/Dockerfile
    depends_on:
     - Database
    networks:
     - studentappnetwork
   