apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: schoolmanagmentsystem-namespace
type: Opaque
data:
  DB_USERNAME: MjEzMDgz # Base64-encoded password (for "213083")
  DB_PASSWORD: VmV6YmExMjMh # Base64-encoded password (for "Vezba123!")