apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  namespace: student-app-namespace
  labels:
    app: mvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvc-app
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mvc-app
    spec:
      containers:
        - name: mvc-app
          image: darkodimitrov/kii_project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: db-connstr-secret
                key: CONN_STR
---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
  namespace: student-app-namespace
  labels:
    app: mvc-service
spec:
  type: ClusterIP
  selector:
    app: mvc-app
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8001
---
apiVersion: v1
kind: Secret
metadata:
  name: db-connstr-secret
  namespace: student-app-namespace
type: Opaque
stringData:
  CONN_STR: Data Source=Database;Initial Catalog=Database;User ID=sa;Password=Vezba123!1;Trust Server Certificate=True
